FROM python:3.11

WORKDIR /app

COPY . /app

RUN pip3 install --upgrade pip \
    && pip3 install h5py \
    && pip3 install tensorflow \
    && pip3 install keras 

RUN pip install --no-cache-dir -r requirements.txt
