class Allergy():
    Milk = "우유"
    Buckwheat = "메밀"
    Peanut = "땅콩"
    Soybean = "대두"
    Wheat = "밀"
    Mackerel = "고등어"
    Crab = "게"
    Shrimp = "새우"
    Pork = "돼지고기"
    Peach = "복숭아"
    Tomato = "토마토"
    Sulfites = "아황산류"
    Walnut = "호두"
    Chicken = "닭고기"
    Beef = "쇠고기"
    Squid = "오징어"
    Shellfish = "조개류"